### ISSUE TITLE
Is deep_sort\deep\checkpoint\ckpt.t7 the reid model trained by fastreid?

### ISSUE THREAD

**Issue by qinyaolong123** [zengwb-lx/Yolov5-Deepsort-Fastreid#10]
Is deep_sort\deep\checkpoint\ckpt.t7 the reid model trained by fastreid?

**Comment by bai-0829** [comment]
那个大概率是deepsort的模型，fastreid的模型在他给的百度云里，放在kd-r34-r101-ibn文件里
