### ISSUE TITLE
在运行person_search_reid.py时出现No object named 'DistillerOverhaul' found in 'META_ARCH' registry!

### ISSUE THREAD

**Issue by ChenShuai-CA** [zengwb-lx/Yolov5-Deepsort-Fastreid#11]
## ❔Question
![image](https://user-images.githubusercontent.com/89435029/184585959-3a144925-d7de-40ae-9931-47abfcf98628.png)

## Additional context
这个问题应该怎么解决，我看了代码中的registry，没看到这个定义在哪里？

**Comment by He139836** [comment]
你用的yaml文件错了，用他在百度网盘上传的config-test.yaml文件
