### ISSUE TITLE
person_search_reid的问题

### ISSUE THREAD

**Issue by Nasturtium-yyc** [zengwb-lx/Yolov5-Deepsort-Fastreid#3]
## ❔Question
请问person_search_reid如何运行？
## Additional context
FileNotFoundError: [Errno 2] No such file or directory: '../../kd-r34-r101_ibn/config-test.yaml'
这个目录下并没有config-test.yaml文件，是需要另建一个吗？

**Comment by xugaoxiang** [comment]
照着kd-r34-r101_ibn下原来的yml文件，写一个就成

**Comment by Super-six-java** [comment]
> ## ❔Question
> 请问person_search_reid如何运行？
> 
> ## Additional context
> FileNotFoundError: [Errno 2] No such file or directory: '../../kd-r34-r101_ibn/config-test.yaml' 这个目录下并没有config-test.yaml文件，是需要另建一个吗？

老哥解决了吗 ，我这边把网盘上的config-test.yaml 放在/kd-r34-r101_ibn 下还是报这个错
